services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: codelens-frontend:latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - PORT=3000
      - NUXT_PUBLIC_API_URL=http://localhost:8003
      - NUXT_PUBLIC_WEBSOCKET_SERVER_URL=ws://localhost:8003
    depends_on:
      - backend
    networks:
      - codelens-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: codelens-backend:latest
    ports:
      - "127.0.0.1:8003:8003"
    environment:
      - PORT=8003
      - CORS_ORIGINS=http://localhost:3000
      - WEBSOCKET_PING_INTERVAL=30
      - WEBSOCKET_TIMEOUT=3600
      - TEST_RUNNER_URL=ws://test-runner:8004/ws
    depends_on:
      - test-runner
    networks:
      - codelens-network
    restart: unless-stopped

  test-runner:
    build:
      context: ./test-runner-docker
      dockerfile: Dockerfile
    image: codelens-test-runner:docker
    ports:
      - "127.0.0.1:8004:8004"
    environment:
      - PORT=8004
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      test-executor:
        condition: service_completed_successfully
    networks:
      - codelens-network
    restart: unless-stopped

  # Build test executor image (used by test-runner to execute tests)
  test-executor:
    build:
      context: ./test-runner-docker
      dockerfile: test-executor.Dockerfile
    image: codelens-test-executor:latest
    command: echo "Test executor image built successfully"
    restart: "no"

networks:
  codelens-network:
    driver: bridge
