# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    command: npm run dev
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ./backend:/app
      - /app/venv
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHON_ENV=development

  test-runner:
    build:
      context: ./test-runner
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ./test-runner:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      - PYTHON_ENV=development
