services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL:-ws://localhost:8002}
    depends_on:
      - backend
    networks:
      - codelens-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - WEBSOCKET_PING_INTERVAL=${WEBSOCKET_PING_INTERVAL:-30}
      - TEST_RUNNER_URL=${TEST_RUNNER_URL:-ws://test-runner:8001}
      - PORT=8002
    depends_on:
      - test-runner
    networks:
      - codelens-network
    restart: unless-stopped

  test-runner:
    build:
      context: ./test-runner
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - KUBERNETES_NAMESPACE=${KUBERNETES_NAMESPACE:-default}
    volumes:
      # Mount kubeconfig for Kubernetes access (Docker Desktop)
      - ${KUBECONFIG_PATH:-~/.kube/config}:/root/.kube/config:ro
    networks:
      - codelens-network
    restart: unless-stopped

networks:
  codelens-network:
    driver: bridge
