services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_URL=${NUXT_PUBLIC_API_URL:-http://localhost:8000}
      - NUXT_PUBLIC_WEBSOCKET_SERVER_URL=${NUXT_PUBLIC_WEBSOCKET_SERVER_URL:-ws://localhost:8000}
    depends_on:
      - backend
    networks:
      - codelens-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - WEBSOCKET_PING_INTERVAL=${WEBSOCKET_PING_INTERVAL:-30}
      - WEBSOCKET_TIMEOUT=${WEBSOCKET_TIMEOUT:-3600}
      - TEST_RUNNER_URL=${TEST_RUNNER_URL:-ws://test-runner:8001/ws}
    depends_on:
      - test-runner
    networks:
      - codelens-network
    restart: unless-stopped

  test-runner:
    build:
      context: ./test-runner
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - codelens-network
    restart: unless-stopped

networks:
  codelens-network:
    driver: bridge
