apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelens-test-runner
  labels:
    app: codelens
    component: test-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codelens
      component: test-runner
  template:
    metadata:
      labels:
        app: codelens
        component: test-runner
    spec:
      serviceAccountName: test-runner-sa
      containers:
        - name: test-runner
          image: codelens-test-runner:latest
          imagePullPolicy: IfNotPresent  # Try local first, then pull if needed
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: codelens-test-runner
  labels:
    app: codelens
    component: test-runner
spec:
  selector:
    app: codelens
    component: test-runner
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
