<script setup lang="ts">
const workflowSteps = [
  {
    title: 'Paste Your Code',
    description: 'Simply paste your Python function into our editor.',
    icon: 'mdi-code-brackets',
    color: 'primary',
  },
  {
    title: 'Provide AI API Key',
    description: 'Optionally enter your AI API key for enhanced features.',
    icon: 'mdi-key-variant',
    color: 'secondary',
  },
  {
    title: 'Generate and run tests & documentation & optimization tips',
    description: 'Get comprehensive test cases, documentation, and optimization tips generated by AI.',
    icon: 'mdi-auto-fix',
    color: 'secondary',
  },
]

const benefits = [
  {
    title: 'Save Development Time',
    description: 'Reduce testing time by 80% with automated test generation and execution.',
    icon: 'mdi-clock-fast',
  },
  {
    title: 'Improve Code Quality',
    description: 'Catch edge cases and bugs early with comprehensive AI-generated test coverage.',
    icon: 'mdi-shield-check',
  },
  {
    title: 'Learn Best Practices',
    description: 'Get personalized tips and suggestions to improve your coding skills.',
    icon: 'mdi-school',
  },
  {
    title: 'No Setup Required',
    description: 'Start testing immediately without any complex configuration or installation.',
    icon: 'mdi-lightning-bolt',
  },
]
</script>

<template>
  <div class="home-page">
    <!-- Hero Section -->
    <v-container class="hero-section py-16">
      <v-row
        align="center"
        justify="center"
        class="min-height-screen"
      >
        <v-col
          cols="12"
          md="8"
          lg="6"
          class="text-center"
        >
          <!-- Main Title with Gradient -->
          <h1 class="hero-title mb-6">
            <span class="gradient-text">AI-Powered</span>

            <br>
            Code Testing & Documentation
          </h1>

          <!-- Subtitle -->
          <p class="text-h6 hero-subtitle mb-8">
            Transform your code snippets into comprehensive test suites and documentation
            with the power of AI. Write better code, faster.
          </p>

          <!-- Feature Highlights -->
          <v-row class="mb-8">
            <v-col
              cols="12"
              sm="4"
            >
              <div class="feature-highlight">
                <v-icon
                  size="48"
                  color="primary"
                  class="mb-3"
                >
                  mdi-test-tube
                </v-icon>

                <h3 class="text-h6 mb-2">
                  Auto Test Generation
                </h3>

                <p class="text-medium-emphasis text-body-2">
                  Generate comprehensive test cases automatically from your functions
                </p>
              </div>
            </v-col>

            <v-col
              cols="12"
              sm="4"
            >
              <div class="feature-highlight">
                <v-icon
                  size="48"
                  color="secondary"
                  class="mb-3"
                >
                  mdi-play-circle
                </v-icon>

                <h3 class="text-h6 mb-2">
                  Instant Execution
                </h3>

                <p class="text-body-2 text-medium-emphasis">
                  Run tests immediately and see results in real-time
                </p>
              </div>
            </v-col>

            <v-col
              cols="12"
              sm="4"
            >
              <div class="feature-highlight">
                <v-icon
                  size="48"
                  color="accent"
                  class="mb-3"
                >
                  mdi-book-open-variant
                </v-icon>

                <h3 class="text-h6 mb-2">
                  Smart Documentation
                </h3>

                <p class="text-body-2 text-medium-emphasis">
                  Get AI-generated docs and optimization tips for your code
                </p>
              </div>
            </v-col>
          </v-row>

          <!-- CTA Button -->
          <v-btn
            size="x-large"
            color="primary"
            variant="flat"
            rounded="xl"
            class="cta-button px-8 py-4"
            elevation="8"
          >
            <v-icon start>
              mdi-rocket-launch
            </v-icon>
            Get Started
          </v-btn>
        </v-col>
      </v-row>
    </v-container>

    <!-- Features Section -->
    <v-container class="features-section py-16">
      <v-row>
        <v-col
          cols="12"
          class="mb-12 text-center"
        >
          <h2 class="text-h3 mb-4">
            How It Works
          </h2>

          <p class="text-h6 text-medium-emphasis max-width-600 mx-auto">
            Simple, powerful workflow that takes your code from snippet to production-ready
          </p>
        </v-col>
      </v-row>

      <v-row class="workflow-steps">
        <v-col
          v-for="(step, index) in workflowSteps"
          :key="index"
          cols="12"
          md="4"
        >
          <v-card
            class="workflow-card h-100 pa-6"
            :color="`${step.color}-transparent`"
            elevation="4"
          >
            <div class="text-center">
              <div class="step-number mb-4">
                <v-avatar
                  size="64"
                  :color="step.color"
                  class="text-h4 font-weight-bold"
                >
                  {{ index + 1 }}
                </v-avatar>
              </div>

              <v-icon
                :icon="step.icon"
                size="56"
                :color="step.color"
                class="mb-4"
              />

              <h3 class="text-h5 mb-3">
                {{ step.title }}
              </h3>

              <p class="text-body-1 text-medium-emphasis">
                {{ step.description }}
              </p>
            </div>
          </v-card>
        </v-col>
      </v-row>
    </v-container>

    <!-- Benefits Section -->
    <v-container class="benefits-section py-16">
      <v-row justify="center">
        <v-col
          cols="12"
          md="8"
          lg="6"
        >
          <h2 class="text-h3 mb-6 text-center">
            Why Choose Our Platform?
          </h2>

          <v-list
            class="benefits-list"
            lines="two"
          >
            <v-list-item
              v-for="benefit in benefits"
              :key="benefit.title"
              :prepend-icon="benefit.icon"
              class="mb-2"
            >
              <v-list-item-title class="text-h6 mb-1">
                {{ benefit.title }}
              </v-list-item-title>

              <v-list-item-subtitle class="text-body-1">
                {{ benefit.description }}
              </v-list-item-subtitle>
            </v-list-item>
          </v-list>
        </v-col>
      </v-row>
    </v-container>

    <!-- API Key Section -->
    <v-container class="api-section py-16">
      <v-row justify="center">
        <v-col
          cols="12"
          md="8"
          lg="6"
          class="text-center"
        >
          <v-card
            class="api-card pa-8"
            color="primary-transparent"
            elevation="12"
          >
            <v-icon
              size="64"
              color="primary"
              class="mb-4"
            >
              mdi-key-variant
            </v-icon>

            <h2 class="text-h4 mb-4">
              Unlock AI Features
            </h2>

            <p class="text-h6 text-medium-emphasis mb-6">
              Provide your LLM API key to access AI-powered documentation generation,
              code optimization tips, and enhanced test suggestions.
            </p>

            <v-alert
              type="info"
              class="mb-6"
              icon="mdi-information"
            >
              <strong>Optional:</strong> You can still generate and run basic tests without an API key.
              AI features require a valid OpenAI, Anthropic, or compatible API key.
            </v-alert>

            <v-btn
              size="large"
              color="primary"
              variant="flat"
              rounded="xl"
              class="px-6"
            >
              <v-icon start>
                mdi-key
              </v-icon>
              Configure API Key
            </v-btn>
          </v-card>
        </v-col>
      </v-row>
    </v-container>

    <!-- Footer CTA -->
    <v-container class="footer-cta py-16">
      <v-row justify="center">
        <v-col
          cols="12"
          class="text-center"
        >
          <h2 class="text-h3 mb-4">
            Ready to Test Smarter?
          </h2>

          <p class="text-h6 text-medium-emphasis mb-8">
            Start generating comprehensive tests and documentation for your code today.
          </p>

          <v-btn
            size="x-large"
            color="accent"
            variant="flat"
            rounded="xl"
            class="mb-4 mr-4"
          >
            <v-icon start>
              mdi-play
            </v-icon>
            Start Testing
          </v-btn>

          <v-btn
            size="x-large"
            variant="outlined"
            rounded="xl"
            class="mb-4"
          >
            <v-icon start>
              mdi-github
            </v-icon>
            View on GitHub
          </v-btn>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style scoped>
.home-page {
  min-height: 100vh;
}

.hero-section {
  background: linear-gradient(135deg, rgb(var(--v-theme-primary-lighten-1), 0.1) 0%, rgb(var(--v-theme-secondary-lighten-1), 0.1) 100%);
  position: relative;
}

.hero-section::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-image:
    radial-gradient(circle at 20% 50%, rgb(var(--v-theme-info), 0.1) 0%, transparent 50%),
    radial-gradient(circle at 80% 20%, rgb(var(--v-theme-error), 0.1) 0%, transparent 50%);
  pointer-events: none;
}

.min-height-screen {
  min-height: 80vh;
}

.hero-title {
  font-size: clamp(2.5rem, 5vw, 4rem);
  font-weight: 700;
  line-height: 1.2;
  margin-bottom: 2rem;
}

.gradient-text {
  background: linear-gradient(45deg, rgb(var(--v-theme-primary-lighten-1)), rgb(var(--v-theme-info)));
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-size: 200% 200%;
  animation: gradient-shift 3s ease-in-out infinite;
}

@keyframes gradient-shift {
  0%, 100% { background-position: 0% 50%; }
  50% { background-position: 100% 50%; }
}

.hero-subtitle {
  max-width: 600px;
  margin: 0 auto;
  opacity: 0.9;
}

.feature-highlight {
  padding: 1.5rem;
  transition: transform 0.3s ease;
}

.feature-highlight:hover {
  transform: translateY(-8px);
}

.cta-button {
  transition: all 0.3s ease;
  box-shadow: 0 8px 32px rgb(var(--v-theme-primary-lighten-1), 0.3) !important;
}

.cta-button:hover {
  transform: translateY(-2px);
  box-shadow: 0 12px 40px rgb(var(--v-theme-primary-lighten-1), 0.4) !important;
}

.workflow-card {
  transition: all 0.3s ease;
  border: 1px solid rgba(255, 255, 255, 0.1);
}

.workflow-card:hover {
  transform: translateY(-8px);
  box-shadow: 0 16px 48px rgba(0, 0, 0, 0.2) !important;
}

.step-number {
  position: relative;
}

.benefits-list .v-list-item {
  padding-left: 0;
  margin-bottom: 1rem;
}

.api-card {
  position: relative;
  backdrop-filter: blur(10px);
  border: 1px solid rgb(var(--v-theme-primary-lighten-1), 0.2);
}

.max-width-600 {
  max-width: 600px;
}

.features-section {
  background: linear-gradient(180deg, transparent 0%, rgb(var(--v-theme-secondary-lighten-1), 0.05) 100%);
}

.benefits-section {
  background: rgb(var(--v-theme-primary-lighten-1), 0.05);
}

.api-section {
  background: linear-gradient(135deg, rgb(var(--v-theme-info), 0.05) 0%, rgb(var(--v-theme-secondary-lighten-1), 0.05) 100%);
}

@media (max-width: 960px) {
  .hero-section {
    padding-top: 2rem;
    padding-bottom: 2rem;
  }

  .min-height-screen {
    min-height: 60vh;
  }

  .workflow-steps .v-col {
    margin-bottom: 1rem;
  }
}
</style>
