apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-runner-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-runner-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-runner-rolebinding
subjects:
- kind: ServiceAccount
  name: test-runner-sa
roleRef:
  kind: Role
  name: test-runner-role
  apiGroup: rbac.authorization.k8s.io
