<script setup lang="ts">
import { useStepperNavigation } from '~/composables/useStepperNavigation'

const { goNext, canGoNext, nextStepName } = useStepperNavigation()

const workflowSteps = [
  {
    title: 'Paste Your Code',
    description: 'Simply paste your Python function into our editor.',
    icon: 'mdi-code-brackets',
    color: 'primary',
  },
  {
    title: 'Provide AI API Key',
    description: 'Optionally enter your AI API key for enhanced features.',
    icon: 'mdi-key-variant',
    color: 'secondary',
  },
  {
    title: 'Generate Insights',
    description: 'Get comprehensive test cases, documentation, and optimization tips generated by AI.',
    icon: 'mdi-auto-fix',
    color: 'accent',
  },
]

const benefits = [
  {
    title: 'Save Development Time',
    description: 'Reduce testing time by 80% with automated test generation and execution.',
    icon: 'mdi-clock-fast',
    color: 'primary',
  },
  {
    title: 'Improve Code Quality',
    description: 'Catch edge cases and bugs early with comprehensive AI-generated test coverage.',
    icon: 'mdi-shield-check',
    color: 'secondary',
  },
  {
    title: 'Learn Best Practices',
    description: 'Get personalized tips and suggestions to improve your coding skills.',
    icon: 'mdi-school',
    color: 'accent',
  },
  {
    title: 'No Setup Required',
    description: 'Start testing immediately without any complex configuration or installation.',
    icon: 'mdi-lightning-bolt',
    color: 'info',
  },
]
</script>

<template>
  <div class="home-page">
    <!-- Hero Section -->
    <v-container class="hero-section py-16">
      <v-row
        align="center"
        justify="center"
        class="min-h-[80vh]"
      >
        <v-col
          cols="12"
          md="10"
          lg="8"
          class="text-center"
        >
          <!-- Main Title with Gradient -->
          <h1 class="hero-title mb-6 font-bold">
            <span class="gradient-text">AI-Powered</span>

            <br>
            Code Testing & Documentation
          </h1>

          <!-- Subtitle -->
          <p class="text-h6 text-medium-emphasis mx-auto mb-8 max-w-[600px]">
            Transform your code snippets into comprehensive test suites and documentation
            with the power of AI. Write better code, faster.
          </p>

          <!-- Feature Highlights -->
          <v-row class="mb-8">
            <v-col
              v-for="feature in [
                {'title': 'Auto Test Generation',
                 'text': 'Generate comprehensive test cases automatically from your functions',
                 'icon': 'mdi-test-tube',
                 'color': 'primary'},
                {'title': 'Instant Execution',
                 'text': 'Run tests immediately and see results in real-time',
                 'icon': 'mdi-play-circle-outline',
                 'color': 'secondary'},
                {'title': 'Smart Documentation',
                 'text': 'Get AI-generated docs and optimization tips for your code',
                 'icon': 'mdi-book-open-variant',
                 'color': 'accent'},
              ]"
              :key="feature.title"
              cols="12"
              sm="4"
            >
              <div class="feature-highlight pa-6">
                <v-icon
                  :icon="feature.icon"
                  :color="feature.color"
                  size="48"
                  class="mb-3"
                />

                <h3 class="text-h6 mb-2">
                  {{ feature.title }}
                </h3>

                <p class="text-body-2 text-medium-emphasis">
                  {{ feature.text }}
                </p>
              </div>
            </v-col>
          </v-row>

          <!-- CTA Button -->
          <v-btn
            size="x-large"
            color="primary"
            variant="flat"
            class="cta-button px-8 py-4"
            @click="goNext"
          >
            <v-icon
              start
              icon="mdi-rocket-launch-outline"
            />
            Get Started
          </v-btn>
        </v-col>
      </v-row>
    </v-container>

    <!-- How It Works Section -->
    <v-container class="py-16">
      <v-row justify="center">
        <v-col
          cols="12"
          class="mb-12 text-center"
        >
          <h2 class="text-h3 mb-4">
            How It Works
          </h2>

          <p class="text-h6 text-medium-emphasis mx-auto max-w-[600px]">
            A simple, powerful workflow that takes your code from snippet to production-ready.
          </p>
        </v-col>
      </v-row>

      <v-row class="workflow-steps">
        <v-col
          v-for="(step, index) in workflowSteps"
          :key="index"
          cols="12"
          md="4"
        >
          <v-card
            class="workflow-card h-full pa-6 text-center"
            variant="tonal"
            :color="step.color"
          >
            <div class="mb-4">
              <v-avatar
                size="64"
                :color="step.color"
                class="text-h4 font-weight-bold"
              >
                <span class="text-on-primary">{{ index + 1 }}</span>
              </v-avatar>
            </div>

            <v-icon
              :icon="step.icon"
              size="56"
              :color="step.color"
              class="mb-4"
            />

            <h3 class="text-h5 mb-3">
              {{ step.title }}
            </h3>

            <p class="text-body-1 text-medium-emphasis">
              {{ step.description }}
            </p>
          </v-card>
        </v-col>
      </v-row>
    </v-container>

    <!-- Benefits Section -->
    <v-container class="py-16">
      <v-row justify="center">
        <v-col
          cols="12"
          md="10"
          lg="8"
        >
          <h2 class="text-h3 mb-12 text-center">
            Why Choose Our Platform?
          </h2>

          <v-list
            lines="two"
            bg-color="transparent"
          >
            <v-list-item
              v-for="benefit in benefits"
              :key="benefit.title"
              class="mb-4"
            >
              <template #prepend>
                <v-avatar
                  :color="`${benefit.color}`"
                  variant="tonal"
                  class="mr-4"
                >
                  <v-icon :icon="benefit.icon" />
                </v-avatar>
              </template>

              <v-list-item-title class="text-h6 font-weight-bold mb-1">
                {{ benefit.title }}
              </v-list-item-title>

              <v-list-item-subtitle class="text-body-1 text-medium-emphasis">
                {{ benefit.description }}
              </v-list-item-subtitle>
            </v-list-item>
          </v-list>
        </v-col>
      </v-row>
    </v-container>

    <!-- API Key Section -->
    <v-container class="py-16">
      <v-row justify="center">
        <v-col
          cols="12"
          md="8"
        >
          <v-card
            class="api-card pa-8 text-center"
            variant="tonal"
            color="primary"
          >
            <v-icon
              icon="mdi-key-chain-variant"
              size="64"
              color="primary"
              class="mb-4"
            />

            <h2 class="text-h4 mb-4">
              Unlock Full AI Power
            </h2>

            <p class="text-h6 text-medium-emphasis mb-6">
              Provide your LLM API key to access AI-powered documentation, code optimization, and enhanced test suggestions.
            </p>
            <!-- UPDATED V-ALERT -->
            <v-alert
              variant="tonal"
              color="info"
              border="start"
              density="compact"
              class="mb-6 text-left"
              icon="mdi-information-outline"
            >
              <strong>Optional:</strong> You can still generate and run basic tests without an API key.
            </v-alert>

            <v-btn
              size="large"
              color="primary"
              variant="flat"
              @click="goNext"
            >
              <v-icon
                start
                icon="mdi-key-outline"
              />
              Configure API Key
            </v-btn>
          </v-card>
        </v-col>
      </v-row>
    </v-container>

    <!-- Footer CTA -->
    <v-container class="py-16">
      <v-row justify="center">
        <v-col
          cols="12"
          class="text-center"
        >
          <h2 class="text-h3 mb-4">
            Ready to Test Smarter?
          </h2>

          <p class="text-h6 text-medium-emphasis mb-8">
            Start generating comprehensive tests and documentation for your code today.
          </p>

          <div class="d-flex ga-4 flex-wrap justify-center">
            <v-btn
              size="x-large"
              color="accent"
              variant="flat"
              @click="goNext"
            >
              <v-icon
                start
                icon="mdi-play-outline"
              />
              Start Testing
            </v-btn>

            <v-btn
              size="x-large"
              href="https://github.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              <v-icon
                start
                icon="mdi-github"
              />
              View on GitHub
            </v-btn>
          </div>
        </v-col>
      </v-row>
    </v-container>

    <!-- Navigation Section -->
    <v-divider class="my-6" />

    <v-container>
      <v-row justify="end">
        <v-col cols="auto">
          <v-btn
            v-if="canGoNext"
            color="primary"
            @click="goNext"
          >
            {{ nextStepName }}
            <v-icon
              end
              icon="mdi-arrow-right"
            />
          </v-btn>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style scoped>
.home-page {
  /* Use surface-variant for a subtle off-background color */
  background-color: rgb(var(--v-theme-surface-variant));
}

.hero-section {
  /* A subtle gradient using theme colors for the background */
  background: linear-gradient(135deg, rgba(var(--v-theme-primary), 0.05) 0%, rgba(var(--v-theme-secondary), 0.05) 100%);
  position: relative;
  overflow: hidden;
}

.hero-section::before {
  /* Soft, blurred circles of color for a modern feel */
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-image:
    radial-gradient(circle at 15% 30%, rgba(var(--v-theme-info), 0.1) 0%, transparent 40%),
    radial-gradient(circle at 85% 70%, rgba(var(--v-theme-accent), 0.1) 0%, transparent 40%);
  filter: blur(60px);
  pointer-events: none;
}

.hero-title {
  /* Fluid typography that adapts to screen size */
  font-size: clamp(2.5rem, 5vw, 4rem);
  line-height: 1.2;
}

.gradient-text {
  /* Animated gradient text using theme colors */
  background: linear-gradient(45deg, rgb(var(--v-theme-primary)), rgb(var(--v-theme-info)), rgb(var(--v-theme-accent)));
  background-clip: text;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-size: 200% 200%;
  animation: gradient-shift 5s ease-in-out infinite;
}

@keyframes gradient-shift {
  0%, 100% { background-position: 0% 50%; }
  50% { background-position: 100% 50%; }
}

.feature-highlight {
  /* Smooth transition for hover effects */
  transition: all 0.3s ease-in-out;
  border-radius: 16px; /* Corresponds to v-card rounded='xl' */
}

.feature-highlight:hover {
  /* Lift effect and subtle background on hover */
  transform: translateY(-8px);
  background: rgba(var(--v-theme-on-surface), 0.05);
}

.cta-button {
  transition: all 0.3s ease;
  /* Shadow using theme color for consistency */
  box-shadow: 0 8px 24px rgba(var(--v-theme-primary), 0.3) !important;
}

.cta-button:hover {
  transform: translateY(-2px);
  box-shadow: 0 12px 32px rgba(var(--v-theme-primary), 0.4) !important;
}

.workflow-card {
  transition: all 0.3s ease-in-out;
}

.workflow-card:hover {
  transform: translateY(-8px);
  /* Use a slightly stronger shadow on hover */
  box-shadow: 0 12px 32px rgba(var(--v-theme-shadow-color), 0.15) !important;
}

/* Define a theme-aware shadow color variable */
:root {
  --v-theme-shadow-color: 0, 0, 0;
}
.v-theme--dark:root {
  --v-theme-shadow-color: 255, 255, 255;
}
</style>
