apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelens-test-runner
  labels:
    app: codelens
    component: test-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codelens
      component: test-runner
  template:
    metadata:
      labels:
        app: codelens
        component: test-runner
    spec:
      serviceAccountName: test-runner-sa
      containers:
        - name: test-runner
          image: {{REGISTRY}}/codelens-test-runner:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: codelens-test-runner
  labels:
    app: codelens
    component: test-runner
spec:
  selector:
    app: codelens
    component: test-runner
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
